apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-vibes-ingress
  namespace: dev-vibes
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: dev-vibes.local # Replace with your production domain name (e.g., dev-vibes.com)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-vibes-service
                port:
                  number: 80
  # TLS / SSL Config Placeholder
  # tls:
  #   - hosts:
  #       - dev-vibes.local
  #     secretName: dev-vibes-tls-secret
